/* MODO ADMINISTRADOR — controle de inclusão no balanço */
(function(){
'use strict';
const PASS=[57,53,56,52,50,54,53,57].map(x=>String.fromCharCode(x)).join('');
let admin=false;const $=id=>document.getElementById(id);
function install(){const head=document.querySelector('#services .head');if(!head||$('adminModeBtn'))return;const b=document.createElement('button');b.id='adminModeBtn';b.className='btn';b.textContent='🔒 Administrador';b.title='Área administrativa';b.onclick=()=>{if(admin){admin=false;b.textContent='🔒 Administrador';decorate();return}const p=prompt('Senha de administrador:');if(p===PASS){admin=true;b.textContent='🔓 Administrador ativo';decorate();if(typeof toast==='function')toast('Modo administrador ativado')}else if(p!==null&&typeof toast==='function')toast('Senha incorreta')};head.appendChild(b);decorate()}
async function toggle(id,checked){if(!admin)return;const r=await sb.from('orders').update({exclude_from_balance:checked}).eq('id',id);if(r.error){if(typeof toast==='function')toast('Erro ao atualizar: '+r.error.message);return}const o=(window.orders||[]).find(x=>x.id===id);if(o){o.exclude_from_balance=checked;(o.order_items||[]).forEach(i=>i.exclude_from_balance=checked)}if(typeof toast==='function')toast(checked?'Serviço retirado do balanço':'Serviço incluído novamente no balanço');if(typeof window.renderBalance==='function')window.renderBalance()}
function decorate(){const list=$('allServicesList');if(!list)return;list.querySelectorAll('.service-card').forEach(card=>{let box=card.querySelector('.admin-balance-control');if(!admin){if(box)box.remove();return}const id=card.dataset.orderId||card.dataset.id;if(!id)return;const o=(window.orders||[]).find(x=>x.id===id);if(!box){box=document.createElement('label');box.className='admin-balance-control';box.style.cssText='display:flex;align-items:center;gap:7px;margin-top:8px;padding:7px 9px;border:1px dashed #999;border-radius:8px;font-size:12px;font-weight:700';box.innerHTML='<input type="checkbox"> Não considerar no balanço';card.appendChild(box);box.querySelector('input').onchange=e=>toggle(id,e.target.checked)}box.querySelector('input').checked=!!o?.exclude_from_balance})}
const st=document.createElement('style');st.textContent='.admin-balance-control{background:#fff8df;color:#5a4700}.admin-balance-control input{width:16px;height:16px}';document.head.appendChild(st);
let n=0;const t=setInterval(()=>{install();decorate();if(++n>120)clearInterval(t)},300);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
window.__adminMode=()=>admin;
})();