/* FRETE — implementação única e estável. */
(function(){
'use strict';
const $=id=>document.getElementById(id);
const moneyF=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(n)||0);
const parseF=v=>{let s=String(v??'').replace('R$','').replace(/\s/g,'');if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');return Number(s)||0};
function installCss(){if($('frete-clean-css'))return;const s=document.createElement('style');s.id='frete-clean-css';s.textContent=`
.svc-head,.svc-row{grid-template-columns:minmax(210px,3fr) minmax(105px,1.15fr) minmax(105px,1.15fr) minmax(105px,1.15fr) minmax(85px,1fr) minmax(135px,1.4fr) 36px!important}
#rows .freight-field{width:100%;box-sizing:border-box;padding:9px;border:1px solid #d5dde8;border-radius:8px;background:#fff}
.edit-svc-head,.edit-svc-row{grid-template-columns:minmax(200px,3fr) minmax(95px,1.1fr) minmax(95px,1.1fr) minmax(95px,1.1fr) minmax(80px,1fr) minmax(135px,1.4fr) 36px!important;min-width:880px}
.edit-svc-row .freight-field{width:100%;box-sizing:border-box;padding:8px;border:1px solid #d5dde8;border-radius:8px;background:#fff}`;document.head.appendChild(s)}
function addHeader(sel){const h=document.querySelector(sel);if(!h||h.querySelector('.freight-head'))return;const a=h.querySelectorAll('span');if(a.length>=3){const x=document.createElement('span');x.className='freight-head';x.textContent='Frete';a[2].after(x)}}
function decorateRow(r,item){if(!r||r.querySelector('.freight-field'))return;const tax=r.querySelector('.tax');if(!tax)return;const x=document.createElement('input');x.className='freight-field money';x.inputMode='decimal';x.placeholder='R$ 0,00';const v=Number(item?.freight_value||0);x.value=v?moneyF(v):'';tax.before(x);x.addEventListener('input',calc);x.addEventListener('blur',()=>{const n=parseF(x.value);x.value=n?moneyF(n):'';calc()})}
function items(){return [...document.querySelectorAll('#rows .svc-row')].map(r=>({description:r.querySelector('.desc')?.value.trim()||'',sale_value:parseF(r.querySelector('.sale')?.value),cost_value:parseF(r.querySelector('.cost')?.value),freight_value:parseF(r.querySelector('.freight-field')?.value),tax_rate:Number(r.querySelector('.tax')?.value)||0,service_status:r.querySelector('.status')?.value||'Liberado'})).filter(x=>x.description||x.sale_value||x.cost_value||x.freight_value)}
function calc(){const a=items(),s=a.reduce((t,x)=>t+x.sale_value,0),c=a.reduce((t,x)=>t+x.cost_value,0),f=a.reduce((t,x)=>t+x.freight_value,0),tx=a.reduce((t,x)=>t+x.sale_value*x.tax_rate/100,0);if($('saleTotal'))$('saleTotal').textContent=moneyF(s);if($('costTotal'))$('costTotal').textContent=moneyF(c);if($('taxTotal'))$('taxTotal').textContent=moneyF(tx);if($('profitTotal'))$('profitTotal').textContent=moneyF(s-c-f-tx);if($('grand'))$('grand').textContent=moneyF(s)}
function decorateMain(){installCss();addHeader('.svc-head');document.querySelectorAll('#rows .svc-row').forEach(r=>decorateRow(r));calc()}
function editItems(){return [...document.querySelectorAll('#fixRows .edit-svc-row')].map(r=>({description:r.querySelector('.fd')?.value.trim()||'',sale_value:parseF(r.querySelector('.fs')?.value),cost_value:parseF(r.querySelector('.fc')?.value),freight_value:parseF(r.querySelector('.freight-field')?.value),tax_rate:Number(r.querySelector('.ft')?.value)||0,service_status:r.querySelector('.fst')?.value||'Pronto entregue'})).filter(x=>x.description||x.sale_value||x.cost_value||x.freight_value)}
function calcEdit(){const a=editItems(),s=a.reduce((t,x)=>t+x.sale_value,0),c=a.reduce((t,x)=>t+x.cost_value,0),f=a.reduce((t,x)=>t+x.freight_value,0),tx=a.reduce((t,x)=>t+x.sale_value*x.tax_rate/100,0);if($('fixSale'))$('fixSale').textContent=moneyF(s);if($('fixCost'))$('fixCost').textContent=moneyF(c);if($('fixTax'))$('fixTax').textContent=moneyF(tx);if($('fixProfit'))$('fixProfit').textContent=moneyF(s-c-f-tx)}
function decorateEdit(){const box=$('fixRows');if(!box)return;const id=window.__freteEditId || (typeof editing!=='undefined'&&editing?editing.id:null),list=typeof orders!=='undefined'?orders:[],o=id?list.find(x=>x.id===id):null;addHeader('.edit-svc-head');box.querySelectorAll('.edit-svc-row').forEach((r,i)=>{if(r.querySelector('.freight-field'))return;const tax=r.querySelector('.ft');if(!tax)return;const x=document.createElement('input');x.className='freight-field';x.inputMode='decimal';x.placeholder='R$ 0,00';const v=Number(o?.order_items?.[i]?.freight_value||0);x.value=v?moneyF(v):'';tax.before(x);x.addEventListener('input',calcEdit);x.addEventListener('blur',()=>{const n=parseF(x.value);x.value=n?moneyF(n):'';calcEdit()})});calcEdit()}
async function saveMain(e){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();if(typeof company==='undefined'||!company)return toast('Escolha a empresa primeiro');const a=items();if(!a.length)return toast('Adicione pelo menos um serviço ou produto');cloud('Salvando...');let c=clients.find(x=>x.name.toLowerCase()===$('clientInput').value.trim().toLowerCase());if(!c&&$('clientInput').value.trim()){const cr=await sb.from('clients').insert({company_id:company.id,name:$('clientInput').value.trim()}).select().single();if(cr.error){cloud('Erro ao salvar',false);return toast(cr.error.message)}c=cr.data;clients.unshift(c)}const s=a.reduce((t,x)=>t+x.sale_value,0),cst=a.reduce((t,x)=>t+x.cost_value,0),f=a.reduce((t,x)=>t+x.freight_value,0),tx=a.reduce((t,x)=>t+x.sale_value*x.tax_rate/100,0);const p={company_id:company.id,client_id:c?.id||null,entry_date:$('entry').value,exit_date:$('exit').value||null,client_name:$('clientInput').value.trim(),vehicle_make_model:$('vehicle').value.trim(),plate:$('plate').value.trim(),pedido:$('pedido').value.trim(),payment_status:$('payment').value,total_sale:s,total_cost:cst,total_freight:f,total_tax:tx,net_profit:s-cst-f-tx};const id=typeof editing!=='undefined'&&editing?editing.id:null;const r=id?await sb.from('orders').update(p).eq('id',id).select().single():await sb.from('orders').insert(p).select().single();if(r.error){cloud('Erro ao salvar',false);return toast(r.error.message)}if(id){const dr=await sb.from('order_items').delete().eq('order_id',id);if(dr.error){cloud('Erro ao salvar',false);return toast(dr.error.message)}}const ir=await sb.from('order_items').insert(a.map(x=>({...x,order_id:r.data.id})));if(ir.error){cloud('Erro ao salvar',false);return toast('Lançamento salvo, mas os itens falharam: '+ir.error.message)}if(typeof saveCatalog==='function')await saveCatalog(a);if(typeof editing!=='undefined')editing=null;if(typeof clearOrder==='function')clearOrder();await loadData();toast('Lançamento salvo na nuvem')}
async function saveEdit(e){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const id=window.__freteEditId || (typeof editing!=='undefined'&&editing?editing.id:null);if(!id||typeof company==='undefined'||!company)return toast('Nenhum lançamento selecionado.');const a=editItems();if(!a.length)return toast('Adicione pelo menos um serviço ou produto');const old=(typeof orders!=='undefined'?orders:[]).find(x=>x.id===id);if(!old)return;cloud('Salvando...');let c=clients.find(x=>x.name.toLowerCase()===$('fixClient').value.trim().toLowerCase());if(!c&&$('fixClient').value.trim()){const cr=await sb.from('clients').insert({company_id:company.id,name:$('fixClient').value.trim()}).select().single();if(cr.error){cloud('Erro ao salvar',false);return toast(cr.error.message)}c=cr.data;clients.unshift(c)}const s=a.reduce((t,x)=>t+x.sale_value,0),cst=a.reduce((t,x)=>t+x.cost_value,0),f=a.reduce((t,x)=>t+x.freight_value,0),tx=a.reduce((t,x)=>t+x.sale_value*x.tax_rate/100,0);const p={company_id:company.id,client_id:c?.id||old.client_id||null,entry_date:$('fixEntry').value,exit_date:$('fixExit').value||null,client_name:$('fixClient').value.trim(),vehicle_make_model:$('fixVehicle').value.trim(),plate:$('fixPlate').value.trim(),pedido:$('fixPedido').value.trim(),payment_status:$('fixPayment').value,total_sale:s,total_cost:cst,total_freight:f,total_tax:tx,net_profit:s-cst-f-tx};const r=await sb.from('orders').update(p).eq('id',id).select().single();if(r.error){cloud('Erro ao salvar',false);return toast(r.error.message)}const dr=await sb.from('order_items').delete().eq('order_id',id);if(dr.error){cloud('Erro ao salvar',false);return toast(dr.error.message)}const ir=await sb.from('order_items').insert(a.map(x=>({...x,order_id:id})));if(ir.error){cloud('Erro ao salvar',false);return toast('Serviço salvo, mas os itens falharam: '+ir.error.message)}if(typeof saveCatalog==='function')await saveCatalog(a);$('orderFixModal').classList.add('hidden');window.__freteEditId=null;await loadData();toast('Lançamento atualizado')}
function bind(){installCss();decorateMain();const form=$('order');if(form&&!form.dataset.freteCleanBound){form.dataset.freteCleanBound='1';form.addEventListener('submit',saveMain,true)}const editForm=$('fixEditForm');if(editForm&&!editForm.dataset.freteCleanBound){editForm.dataset.freteCleanBound='1';editForm.addEventListener('submit',saveEdit,true)}const add=$('add');if(add&&!add.dataset.freteCleanBound){add.dataset.freteCleanBound='1';add.addEventListener('click',()=>setTimeout(decorateMain,0))}const fixAdd=$('fixAdd');if(fixAdd&&!fixAdd.dataset.freteCleanBound){fixAdd.dataset.freteCleanBound='1';fixAdd.addEventListener('click',()=>setTimeout(decorateEdit,0))}document.querySelectorAll('#launchList [data-edit],#allServicesList [data-edit]').forEach(b=>{if(b.dataset.freteEditBound)return;b.dataset.freteEditBound='1';b.addEventListener('click',()=>{const id=b.dataset.edit;window.__freteEditId=id;setTimeout(decorateEdit,100)},true)});const m=$('orderFixModal');if(m&&!m.classList.contains('hidden'))decorateEdit()}
installCss();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();const obs=new MutationObserver(()=>{clearTimeout(window.__freteTimer);window.__freteTimer=setTimeout(bind,25)});obs.observe(document.body,{childList:true,subtree:true});
})();
