window.SUPABASE_CONFIG={url:'https://uwnzpoqhxioxjegflksv.supabase.co',key:'sb_publishable_WLXH_fefLlSO-r9ebQHAnw_MtUd7w7r'};

// Correcoes da lista de lancamentos: editar, excluir, asterisco preto e opcoes atualizadas.
window.paymentFlag='';

document.addEventListener('DOMContentLoaded',()=>{
  const css=`
.launch-actions{display:flex;align-items:center;gap:4px;flex-shrink:0}.launch-action{border:1px solid var(--line);background:#fff;border-radius:7px;padding:4px 7px;font-size:10px;font-weight:900;cursor:pointer;color:var(--ink)}.launch-action.delete{color:#b42318}.payment-star{color:#000!important;font-weight:1000;font-size:16px;margin-left:5px}.payment-pending{font-weight:1000!important;color:#000!important}.launch-services{display:grid;gap:2px;margin-top:4px}.service-line{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:3px 6px;border-radius:6px;background:#f7f9fc;font-size:10px}.service-line b{font-size:10px}.service-line .service-status{font-weight:900}.service-line.status-Liberado{background:#e8f2ff;color:#2364a9}.service-line.status-Parado{background:#fff3df;color:#9b5c00}.service-line.status-Pronto{background:#eee9ff;color:#6444ad}.service-line.status-Prontoentregue{background:#e6f7ef;color:#087249}.edit-services{border:1px solid var(--line);border-radius:12px;overflow:auto}.edit-svc-head,.edit-svc-row{display:grid;grid-template-columns:minmax(220px,3fr) minmax(110px,1.2fr) minmax(110px,1.2fr) minmax(90px,1fr) minmax(145px,1.4fr) 36px;gap:7px;align-items:center;min-width:780px}.edit-svc-head{padding:8px;background:#f4f7fb;color:#64748b;font-size:10px;font-weight:900;text-transform:uppercase}.edit-svc-row{padding:7px;border-top:1px solid var(--line)}.edit-svc-row input,.edit-svc-row select{width:100%;padding:8px;border:1px solid #d5dde8;border-radius:8px;background:#fff}.edit-totals{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin-top:10px}.edit-total{padding:8px;background:#f7f9fc;border:1px solid var(--line);border-radius:10px}.edit-total small{display:block;color:var(--muted);font-size:10px}.edit-total b{display:block;margin-top:3px;font-size:14px}.order-edit-grid{display:grid;grid-template-columns:repeat(12,1fr);gap:10px}.order-edit-grid .g4{grid-column:span 4}.order-edit-grid .g12{grid-column:1/-1}@media(max-width:700px){.order-edit-grid{grid-template-columns:1fr}.order-edit-grid .g4,.order-edit-grid .g12{grid-column:1}.edit-totals{grid-template-columns:1fr 1fr}}
`;
  document.head.insertAdjacentHTML('beforeend',`<style>${css}</style>`);
  document.body.insertAdjacentHTML('beforeend',`<div id="orderFixModal" class="modal hidden"><div class="modalbox" style="width:min(900px,100%)"><div class="modalhead"><h2>Editar lançamento</h2><button class="btn" id="fixClose">×</button></div><form id="fixEditForm"><div class="order-edit-grid"><div class="field g4"><label>Entrada</label><input id="fixEntry" type="date" required></div><div class="field g4"><label>Saída</label><input id="fixExit" type="date" required></div><div class="field g4"><label>Nome do cliente</label><input id="fixClient" required></div><div class="field g4"><label>Marca e modelo</label><input id="fixVehicle"></div><div class="field g4"><label>Placa</label><input id="fixPlate"></div><div class="field g4"><label>Forma de pagamento</label><select id="fixPayment"><option value="EM ABERTO">EM ABERTO</option><option>Dinheiro</option><option>Cartão</option><option>Pix</option><option>Cheque</option><option>Carteira</option><option>Boleto</option></select></div><div class="g12"><div class="sectiontitle"><h3>Serviços e produtos</h3></div><div class="edit-services"><div class="edit-svc-head"><span>Descrição</span><span>Venda</span><span>Custo</span><span>Alíquota</span><span>Situação</span><span></span></div><div id="fixRows"></div></div><button type="button" class="btn" id="fixAdd">＋ Adicionar serviço / produto</button></div></div><div class="edit-totals"><div class="edit-total"><small>Venda total</small><b id="fixSale">R$ 0,00</b></div><div class="edit-total"><small>Custo total</small><b id="fixCost">R$ 0,00</b></div><div class="edit-total"><small>Imposto</small><b id="fixTax">R$ 0,00</b></div><div class="edit-total"><small>Lucro líquido</small><b id="fixProfit">R$ 0,00</b></div></div><div class="foot" style="justify-content:space-between"><button type="button" class="btn" id="fixDelete" style="color:#b42318;border-color:#f0c9c5">Excluir lançamento</button><div style="display:flex;gap:8px"><button type="button" class="btn" id="fixCancel">Cancelar</button><button class="btn primary">Salvar alterações</button></div></div></form></div></div>`);

  const pay=$('payment');
  if(pay && ![...pay.options].some(o=>o.value==='Boleto')) pay.insertAdjacentHTML('beforeend','<option value="Boleto">Boleto</option>');
  const rows=$('rows');
  function normalizeStatus(s,v){if(!s)return;s.innerHTML='<option value="Pronto entregue">Pronto/Entregue</option><option value="Liberado">Liberado</option><option value="Parado">Parado</option><option value="Pronto">Pronto</option>';s.value=v||'Pronto entregue'}
  if(rows) rows.querySelectorAll('.status').forEach(s=>normalizeStatus(s,s.value));
  if(typeof addRow==='function'){
    const oldAddRow=addRow;
    addRow=function(item={}){oldAddRow({...item,service_status:item.service_status||'Pronto entregue'});const r=$('rows')?.lastElementChild;normalizeStatus(r?.querySelector('.status'),item.service_status||'Pronto entregue')};
  }

  let currentId=null;
  const editRows=()=>[...document.querySelectorAll('#fixRows .edit-svc-row')].map(r=>({description:r.querySelector('.fd').value.trim(),sale_value:parseMoney(r.querySelector('.fs').value),cost_value:parseMoney(r.querySelector('.fc').value),tax_rate:Number(r.querySelector('.ft').value)||0,service_status:r.querySelector('.fst').value})).filter(x=>x.description||x.sale_value||x.cost_value);
  const calcFix=()=>{const a=editRows(),s=a.reduce((t,x)=>t+x.sale_value,0),c=a.reduce((t,x)=>t+x.cost_value,0),tx=a.reduce((t,x)=>t+x.sale_value*x.tax_rate/100,0);$('fixSale').textContent=money(s);$('fixCost').textContent=money(c);$('fixTax').textContent=money(tx);$('fixProfit').textContent=money(s-c-tx)};
  function addFixRow(item={}){const r=document.createElement('div');r.className='edit-svc-row';r.innerHTML=`<input class="fd" list="catalogList" placeholder="Descrição" value="${esc(item.description||'')}"><input class="fs" inputmode="decimal" placeholder="R$ 0,00" value="${item.sale_value?money(item.sale_value):''}"><input class="fc" inputmode="decimal" placeholder="R$ 0,00" value="${item.cost_value?money(item.cost_value):''}"><input class="ft" type="number" min="0" step=".01" placeholder="%" value="${item.tax_rate??''}"><select class="fst"><option value="Pronto entregue">Pronto/Entregue</option><option>Liberado</option><option>Parado</option><option>Pronto</option></select><button type="button" class="btn">×</button>`;$('fixRows').appendChild(r);r.querySelector('.fst').value=item.service_status||'Pronto entregue';r.querySelector('button').onclick=()=>{r.remove();calcFix()};r.querySelectorAll('input,select').forEach(x=>x.oninput=calcFix);['fs','fc'].forEach(k=>{r.querySelector('.'+k).onblur=e=>{const n=parseMoney(e.target.value);e.target.value=n?money(n):'';calcFix()}});calcFix()}
  function closeFix(){$('orderFixModal').classList.add('hidden');currentId=null}
  function openFix(id){const o=orders.find(x=>x.id===id);if(!o)return;currentId=id;$('fixEntry').value=o.entry_date||today();$('fixExit').value=o.exit_date||today();$('fixClient').value=o.client_name||'';$('fixVehicle').value=o.vehicle_make_model||'';$('fixPlate').value=o.plate||'';$('fixPayment').value=o.payment_status||'EM ABERTO';$('fixRows').innerHTML='';(o.order_items||[]).forEach(addFixRow);if(!o.order_items?.length)addFixRow();$('orderFixModal').classList.remove('hidden');calcFix()}
  $('fixClose').onclick=closeFix;$('fixCancel').onclick=closeFix;$('fixAdd').onclick=()=>addFixRow();
  $('fixEditForm').onsubmit=async e=>{e.preventDefault();if(!currentId||!company)return;const a=editRows();if(!a.length)return toast('Adicione pelo menos um serviço ou produto');const old=orders.find(x=>x.id===currentId);if(!old)return;cloud('Salvando...');let c=clients.find(x=>x.name.toLowerCase()===$('fixClient').value.trim().toLowerCase());if(!c&&$('fixClient').value.trim()){const cr=await sb.from('clients').insert({company_id:company.id,name:$('fixClient').value.trim()}).select().single();if(cr.error){cloud('Erro ao salvar',false);return toast(cr.error.message)}c=cr.data}const sale=a.reduce((s,x)=>s+x.sale_value,0),cost=a.reduce((s,x)=>s+x.cost_value,0),tax=a.reduce((s,x)=>s+x.sale_value*x.tax_rate/100,0);const p={company_id:company.id,client_id:c?.id||old.client_id||null,entry_date:$('fixEntry').value,exit_date:$('fixExit').value,client_name:$('fixClient').value.trim(),vehicle_make_model:$('fixVehicle').value.trim(),plate:$('fixPlate').value.trim(),payment_status:$('fixPayment').value,total_sale:sale,total_cost:cost,total_tax:tax,net_profit:sale-cost-tax};const r=await sb.from('orders').update(p).eq('id',currentId).select().single();if(r.error){cloud('Erro ao salvar',false);return toast(r.error.message)}const dr=await sb.from('order_items').delete().eq('order_id',currentId);if(dr.error){cloud('Erro ao salvar',false);return toast(dr.error.message)}const ir=await sb.from('order_items').insert(a.map(x=>({...x,order_id:currentId})));if(ir.error){cloud('Erro ao salvar',false);return toast(ir.error.message)}if(typeof saveCatalog==='function')await saveCatalog(a);closeFix();await loadData();toast('Lançamento atualizado')};
  async function removeOrder(id){const o=orders.find(x=>x.id===id);if(!o)return;if(!confirm('Excluir este lançamento? Esta ação não pode ser desfeita.'))return;cloud('Excluindo...');const r=await sb.from('orders').delete().eq('id',id);if(r.error){cloud('Erro ao excluir',false);return toast(r.error.message)}closeFix();await loadData();toast('Lançamento excluído')}
  $('fixDelete').onclick=()=>{if(currentId)removeOrder(currentId)};
  renderLaunches=function(){updateCatalog();const q=($('launchSearch').value||'').toLowerCase();const a=orders.filter(o=>[o.client_name,o.vehicle_make_model,o.plate,...(o.order_items||[]).map(i=>i.description)].join(' ').toLowerCase().includes(q));$('count').textContent=a.length+' lançamento(s)';$('launchList').innerHTML=a.map(o=>{const first=(o.order_items||[])[0];const st=first?.service_status||'Pronto entregue';const cl=slug(st);const pending=['EM ABERTO','Carteira'].includes(String(o.payment_status||'EM ABERTO').trim());return `<article class="launch ${cl}" data-id="${o.id}"><div class="ltop"><div><div class="lname">${esc(o.client_name||'Sem cliente')}${pending?'<span class="payment-star">★</span>':''}</div><div class="meta">${o.entry_date||''} • Saída ${o.exit_date||''}${o.vehicle_make_model?' • '+esc(o.vehicle_make_model):''}${o.plate?' • '+esc(o.plate):''}</div></div><div class="launch-actions"><b>${money(o.total_sale)}</b><button type="button" class="launch-action" data-edit="${o.id}">Editar</button><button type="button" class="launch-action delete" data-delete="${o.id}">Excluir</button></div></div><div class="launch-services">${(o.order_items||[]).map(i=>`<div class="service-line status-${slug(i.service_status||'Pronto entregue')}"><span><b>${esc(i.description)}</b> • ${money(i.sale_value)}</span><span class="service-status">${esc(i.service_status||'Pronto entregue')}</span></div>`).join('')}</div><div class="chips"><span class="chip ${pending?'payment-pending':''}">${pending?'★ ':''}${esc(o.payment_status||'EM ABERTO')}</span></div></article>`}).join('')||'<div class="empty">Nenhum lançamento encontrado.</div>';$('launchList').querySelectorAll('[data-edit]').forEach(b=>b.onclick=e=>{e.stopPropagation();openFix(b.dataset.edit)});$('launchList').querySelectorAll('[data-delete]').forEach(b=>b.onclick=e=>{e.stopPropagation();removeOrder(b.dataset.delete)});$('launchList').querySelectorAll('.launch').forEach(x=>x.onclick=e=>{if(e.target.closest('[data-edit],[data-delete]'))return;openFix(x.dataset.id)})};
  if($('launchSearch'))$('launchSearch').oninput=renderLaunches;
  setTimeout(()=>{try{renderLaunches()}catch(e){console.error(e)}},50);
});

// Layout dedicado para navegador de celular: navegação inferior, campos maiores, cartões compactos e sem rolagem horizontal da página.
document.addEventListener('DOMContentLoaded',()=>{
  const mobileCss=`
@media(max-width:700px){
  html,body{width:100%;max-width:100%;overflow-x:hidden;-webkit-text-size-adjust:100%}
  body{padding-bottom:72px}
  .top{position:sticky;top:0}
  .topin{padding:9px 10px;min-height:58px;gap:8px;align-items:center}
  .brand{min-width:0;gap:8px}.mark{width:34px;height:34px;border-radius:10px;font-size:12px}.brand b{font-size:14px;white-space:nowrap}.brand small{display:none}
  .actions{margin-left:auto;gap:5px;flex-wrap:nowrap;overflow:hidden}.cloud{display:none}.pill{max-width:120px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;padding:7px 9px;font-size:10px}.actions .btn{padding:8px 9px;font-size:11px}.actions #logout{display:none}
  .shell{display:block;padding:10px 9px 12px;margin:0;max-width:none}
  .side{position:fixed;left:8px;right:8px;bottom:8px;top:auto;z-index:80;height:56px;padding:4px;display:grid;grid-template-columns:repeat(3,1fr);gap:3px;border-radius:16px;box-shadow:0 8px 30px #17203325}
  .nav{min-width:0!important;padding:7px 3px;text-align:center;font-size:11px;border-radius:11px}.nav.active{background:#edf4fc}
  .head{margin:4px 2px 12px;gap:4px}.head h1{font-size:23px}.head p{font-size:12px;line-height:1.35}
  .card{border-radius:15px;padding:11px;margin-bottom:10px;box-shadow:0 5px 18px #1720330c}
  .grid{display:grid;grid-template-columns:1fr!important;gap:9px}.g2,.g3,.g4,.g6,.g8,.g12{grid-column:1!important}
  .field{gap:5px}.field label{font-size:11px}.field input,.field select{min-height:44px;padding:10px 11px;font-size:16px;border-radius:10px}
  .sectiontitle{margin:2px 0 8px}.sectiontitle h3{font-size:15px}.sectiontitle span{font-size:10px}
  .services{overflow-x:auto;-webkit-overflow-scrolling:touch;border-radius:11px}.svc-head,.svc-row{min-width:760px}.svc-head{padding:8px;font-size:9px}.svc-row{padding:7px;gap:6px}.svc-row input,.svc-row select{min-height:40px;padding:8px;font-size:14px}
  #add{width:100%;margin-top:7px;min-height:42px}.totals{grid-template-columns:1fr 1fr;gap:7px;margin-top:10px}.metric{padding:9px;border-radius:10px}.metric small{font-size:10px}.metric b{font-size:15px;margin-top:3px}.grand{font-size:19px;margin-top:10px}.foot{display:grid;grid-template-columns:1fr 1.4fr;margin-top:10px}.foot .btn{min-height:44px}
  .launches{gap:5px}.launch{padding:8px 8px;border-radius:10px}.ltop{align-items:flex-start}.lname{font-size:12px;line-height:1.25}.meta{font-size:9px;line-height:1.35}.launch-actions{gap:3px}.launch-action{padding:5px 6px;font-size:9px}.launch-actions>b{font-size:12px}.payment-star{font-size:14px;margin-left:3px}.launch-services{margin-top:4px}.service-line{font-size:9px;padding:4px 5px;gap:5px}.service-line b{font-size:9px}.service-status{white-space:nowrap}.chips{margin-top:4px}.chip{font-size:9px;padding:3px 5px}
  #launchList .empty{padding:18px 10px}
  .clients{grid-template-columns:1fr!important;gap:7px}.client{padding:11px;border-radius:11px}.client b{font-size:14px}.client small{font-size:11px;margin-top:3px}
  #newClient{width:100%;min-height:42px}.balance{grid-template-columns:1fr 1fr!important;gap:7px}.bcard{padding:11px;border-radius:12px}.bcard b{font-size:18px}.bcard small{font-size:10px}
  #balance .head>div:last-child{display:grid;grid-template-columns:repeat(3,1fr);width:100%;gap:4px}.period{padding:8px 4px;font-size:10px}
  #breakdown>div{grid-template-columns:100px 1fr 25px!important;gap:6px!important;font-size:10px!important}
  .modal{padding:8px;place-items:end center}.modalbox{width:100%!important;max-height:92vh;border-radius:18px 18px 0 0;padding:14px}.modalhead h2{font-size:18px}.modal .field input,.modal .field select{font-size:16px;min-height:44px}
  #orderFixModal .edit-services{overflow-x:auto}.edit-svc-head,.edit-svc-row{min-width:700px}.edit-totals{grid-template-columns:1fr 1fr}.edit-total{padding:8px}.edit-total b{font-size:13px}
  #orderFixModal .foot{display:flex;flex-direction:column}.order-edit-grid{grid-template-columns:1fr!important}.order-edit-grid .g4,.order-edit-grid .g12{grid-column:1!important}.order-edit-grid+.edit-totals{margin-top:8px}
  .toast{left:10px;right:10px;bottom:74px;text-align:center;font-size:12px}
}
@media(min-width:701px) and (max-width:1000px){.shell{padding:16px}.topin{padding:12px 16px}}
`;
  document.head.insertAdjacentHTML('beforeend',`<style id="mobile-layout">${mobileCss}</style>`);
});