window.SUPABASE_CONFIG={url:'https://uwnzpoqhxioxjegflksv.supabase.co',key:'sb_publishable_WLXH_fefLlSO-r9ebQHAnw_MtUd7w7r'};

// UI overrides: compact launch cards + edit/delete popup.
document.addEventListener('DOMContentLoaded',()=>{
  const css=`
.launches{gap:3px}.launch{padding:5px 8px;border-radius:9px}.lname{font-size:13px}.meta{font-size:10px;margin-top:1px}.chips{gap:3px;margin-top:3px}.chip{padding:2px 5px;font-size:9px}.launch-actions{display:flex;align-items:center;gap:4px;flex-shrink:0}.launch-action{border:1px solid var(--line);background:#fff;border-radius:7px;padding:3px 6px;font-size:10px;font-weight:900;cursor:pointer;color:var(--ink)}.launch-action.delete{color:#b42318}.order-edit-grid{display:grid;grid-template-columns:repeat(12,1fr);gap:10px}.order-edit-grid .g4{grid-column:span 4}.order-edit-grid .g8{grid-column:span 8}.order-edit-grid .g12{grid-column:1/-1}.edit-services{border:1px solid var(--line);border-radius:12px;overflow:auto}.edit-svc-head,.edit-svc-row{display:grid;grid-template-columns:minmax(220px,3fr) minmax(110px,1.2fr) minmax(110px,1.2fr) minmax(90px,1fr) minmax(145px,1.4fr) 36px;gap:7px;align-items:center;min-width:780px}.edit-svc-head{padding:8px;background:#f4f7fb;color:#64748b;font-size:10px;font-weight:900;text-transform:uppercase}.edit-svc-row{padding:7px;border-top:1px solid var(--line)}.edit-svc-row input,.edit-svc-row select{width:100%;padding:8px;border:1px solid #d5dde8;border-radius:8px;background:#fff}.edit-totals{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin-top:10px}.edit-total{padding:8px;background:#f7f9fc;border:1px solid var(--line);border-radius:10px}.edit-total small{display:block;color:var(--muted);font-size:10px}.edit-total b{display:block;margin-top:3px;font-size:14px}@media(max-width:700px){.order-edit-grid{grid-template-columns:1fr}.order-edit-grid .g4,.order-edit-grid .g8,.order-edit-grid .g12{grid-column:1}.edit-totals{grid-template-columns:1fr 1fr}}
`;
  document.head.insertAdjacentHTML('beforeend',`<style>${css}</style>`);
  document.body.insertAdjacentHTML('beforeend',`<div id="orderModal" class="modal hidden"><div class="modalbox" style="width:min(900px,100%)"><div class="modalhead"><h2>Editar lançamento</h2><button class="btn" id="closeOrderModal">×</button></div><form id="editOrderForm"><div class="order-edit-grid"><div class="field g4"><label>Entrada</label><input id="editEntry" type="date" required></div><div class="field g4"><label>Saída</label><input id="editExit" type="date" required></div><div class="field g4"><label>Nome do cliente</label><input id="editClient" required></div><div class="field g4"><label>Marca e modelo</label><input id="editVehicle"></div><div class="field g4"><label>Placa</label><input id="editPlate"></div><div class="field g4"><label>Forma de pagamento</label><select id="editPayment"><option value="">— Em branco —</option><option>Dinheiro</option><option>Cartão</option><option>Pix</option><option>Cheque</option><option>Carteira</option></select></div><div class="g12"><div class="sectiontitle"><h3>Serviços e produtos</h3><span>Edite os valores e a situação diretamente aqui.</span></div><div class="edit-services"><div class="edit-svc-head"><span>Descrição</span><span>Venda</span><span>Custo</span><span>Alíquota</span><span>Situação</span><span></span></div><div id="editRows"></div></div><button type="button" class="btn" id="addEditRow" style="margin-top:7px">＋ Adicionar serviço / produto</button></div></div><div class="edit-totals"><div class="edit-total"><small>Venda total</small><b id="editSaleTotal">R$ 0,00</b></div><div class="edit-total"><small>Custo total</small><b id="editCostTotal">R$ 0,00</b></div><div class="edit-total"><small>Imposto</small><b id="editTaxTotal">R$ 0,00</b></div><div class="edit-total"><small>Lucro líquido</small><b id="editProfitTotal">R$ 0,00</b></div></div><div class="foot" style="justify-content:space-between"><button type="button" class="btn" id="deleteOrderFromModal" style="color:#b42318;border-color:#f0c9c5">Excluir lançamento</button><div style="display:flex;gap:8px"><button type="button" class="btn" id="cancelOrderModal">Cancelar</button><button class="btn primary">Salvar alterações</button></div></div></form></div></div>`);
  let popupEditingId=null;
  function editRowItems(){return [...document.querySelectorAll('#editRows .edit-svc-row')].map(r=>({description:r.querySelector('.edesc').value.trim(),sale_value:parseMoney(r.querySelector('.esale').value),cost_value:parseMoney(r.querySelector('.ecost').value),tax_rate:Number(r.querySelector('.etax').value)||0,service_status:r.querySelector('.estatus').value})).filter(x=>x.description||x.sale_value||x.cost_value)}
  function calcEdit(){const a=editRowItems(),sale=a.reduce((s,x)=>s+x.sale_value,0),cost=a.reduce((s,x)=>s+x.cost_value,0),tax=a.reduce((s,x)=>s+x.sale_value*x.tax_rate/100,0);$('editSaleTotal').textContent=money(sale);$('editCostTotal').textContent=money(cost);$('editTaxTotal').textContent=money(tax);$('editProfitTotal').textContent=money(sale-cost-tax)}
  function addEditRow(item={}){const r=document.createElement('div');r.className='edit-svc-row';r.innerHTML=`<input class="edesc" list="catalogList" placeholder="Descrição serviço / produto" value="${esc(item.description||'')}"><input class="esale" inputmode="decimal" placeholder="R$ 0,00" value="${item.sale_value?money(item.sale_value):''}"><input class="ecost" inputmode="decimal" placeholder="R$ 0,00" value="${item.cost_value?money(item.cost_value):''}"><input class="etax" type="number" min="0" step=".01" placeholder="%" value="${item.tax_rate??''}"><select class="estatus"><option>Liberado</option><option>Parado</option><option>Pronto</option><option>Pronto entregue</option></select><button type="button" class="btn">×</button>`;$('editRows').appendChild(r);r.querySelector('.estatus').value=item.service_status||'Liberado';r.querySelector('button').onclick=()=>{r.remove();calcEdit()};r.querySelectorAll('input,select').forEach(x=>x.oninput=calcEdit);['esale','ecost'].forEach(k=>{const x=r.querySelector('.'+k);x.onblur=()=>{const n=parseMoney(x.value);x.value=n?money(n):'';calcEdit()}});calcEdit()}
  function openOrderModal(id){const o=orders.find(x=>x.id===id);if(!o)return;popupEditingId=id;$('editEntry').value=o.entry_date||today();$('editExit').value=o.exit_date||today();$('editClient').value=o.client_name||'';$('editVehicle').value=o.vehicle_make_model||'';$('editPlate').value=o.plate||'';$('editPayment').value=o.payment_status||'';$('editRows').innerHTML='';(o.order_items||[]).forEach(addEditRow);if(!o.order_items?.length)addEditRow();calcEdit();$('orderModal').classList.remove('hidden')}
  function closeOrderModal(){$('orderModal').classList.add('hidden');popupEditingId=null}
  $('closeOrderModal').onclick=closeOrderModal;$('cancelOrderModal').onclick=closeOrderModal;$('addEditRow').onclick=()=>addEditRow();
  $('editOrderForm').onsubmit=async e=>{e.preventDefault();if(!popupEditingId||!company)return;const a=editRowItems();if(!a.length)return toast('Adicione pelo menos um serviço ou produto');const o=orders.find(x=>x.id===popupEditingId);if(!o)return;cloud('Salvando...');let c=clients.find(x=>x.name.toLowerCase()===$('editClient').value.trim().toLowerCase());if(!c&&$('editClient').value.trim()){const cr=await sb.from('clients').insert({company_id:company.id,name:$('editClient').value.trim()}).select().single();if(cr.error){cloud('Erro ao salvar',false);return toast(cr.error.message)}c=cr.data;clients.unshift(c)}const sale=a.reduce((s,x)=>s+x.sale_value,0),cost=a.reduce((s,x)=>s+x.cost_value,0),tax=a.reduce((s,x)=>s+x.sale_value*x.tax_rate/100,0);const p={company_id:company.id,client_id:c?.id||null,entry_date:$('editEntry').value,exit_date:$('editExit').value,client_name:$('editClient').value.trim(),vehicle_make_model:$('editVehicle').value.trim(),plate:$('editPlate').value.trim(),payment_status:$('editPayment').value,total_sale:sale,total_cost:cost,total_tax:tax,net_profit:sale-cost-tax};const r=await sb.from('orders').update(p).eq('id',popupEditingId).select().single();if(r.error){cloud('Erro ao salvar',false);return toast(r.error.message)}const dr=await sb.from('order_items').delete().eq('order_id',popupEditingId);if(dr.error){cloud('Erro ao salvar',false);return toast(dr.error.message)}const ir=await sb.from('order_items').insert(a.map(x=>({...x,order_id:popupEditingId})));if(ir.error){cloud('Erro ao salvar',false);return toast(ir.error.message)}await saveCatalog(a);closeOrderModal();await loadData();toast('Lançamento atualizado')};
  async function deleteOrder(id){const o=orders.find(x=>x.id===id);if(!o)return;if(!confirm(`Excluir o lançamento de ${o.client_name||'Sem cliente'}? Esta ação não pode ser desfeita.`))return;cloud('Excluindo...');const r=await sb.from('orders').delete().eq('id',id);if(r.error){cloud('Erro ao excluir',false);return toast(r.error.message)}if(popupEditingId===id)closeOrderModal();await loadData();toast('Lançamento excluído')}
  $('deleteOrderFromModal').onclick=()=>{if(popupEditingId)deleteOrder(popupEditingId)};
  renderLaunches=function(){updateCatalog();const q=($('launchSearch').value||'').toLowerCase();const a=orders.filter(o=>[o.client_name,o.vehicle_make_model,o.plate,...(o.order_items||[]).map(i=>i.description)].join(' ').toLowerCase().includes(q));$('count').textContent=a.length+' lançamento(s)';$('launchList').innerHTML=a.map(o=>{const st=(o.order_items||[])[0]?.service_status||'Liberado',cl=slug(st);return `<article class="launch ${cl}" data-id="${o.id}"><div class="ltop"><div><div class="lname">${esc(o.client_name||'Sem cliente')}</div><div class="meta">${o.entry_date||''} • Saída ${o.exit_date||''}${o.vehicle_make_model?' • '+esc(o.vehicle_make_model):''}${o.plate?' • '+esc(o.plate):''}</div></div><div class="launch-actions"><b>${money(o.total_sale)}</b><button type="button" class="launch-action" data-edit="${o.id}">Editar</button><button type="button" class="launch-action delete" data-delete="${o.id}">Excluir</button></div></div><div class="chips">${(o.order_items||[]).map(i=>`<span class="chip ${slug(i.service_status)}">${esc(i.description)} • ${money(i.sale_value)} • ${esc(i.service_status)}</span>`).join('')}<span class="chip">${esc(o.payment_status||'Pagamento em branco')}</span></div></article>`}).join('')||'<div class="empty">Nenhum lançamento encontrado.</div>';$('launchList').querySelectorAll('.launch').forEach(x=>x.onclick=e=>{if(e.target.closest('[data-edit],[data-delete]'))return;openOrderModal(x.dataset.id)});$('launchList').querySelectorAll('[data-edit]').forEach(b=>b.onclick=e=>{e.stopPropagation();openOrderModal(b.dataset.edit)});$('launchList').querySelectorAll('[data-delete]').forEach(b=>b.onclick=e=>{e.stopPropagation();deleteOrder(b.dataset.delete)})};
  $('launchSearch').oninput=renderLaunches;
  renderLaunches();
});